CREATE TABLE IF NOT EXISTS receipts (
  id VARCHAR(255) PRIMARY KEY,
  donation_id VARCHAR(255) NOT NULL UNIQUE,
  receipt_no VARCHAR(100) NOT NULL UNIQUE,
  pdf_url VARCHAR(255) NOT NULL,
  generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (donation_id) REFERENCES donations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS eighty_g_certificates (
  id VARCHAR(255) PRIMARY KEY,
  donation_id VARCHAR(255) NOT NULL UNIQUE,
  certificate_no VARCHAR(100) NOT NULL UNIQUE,
  pdf_url VARCHAR(255) NOT NULL,
  generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (donation_id) REFERENCES donations(id) ON DELETE CASCADE
);
