ALTER TABLE donations
  ADD COLUMN guest_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN guest_email VARCHAR(255) DEFAULT NULL,
  ADD COLUMN guest_phone VARCHAR(50) DEFAULT NULL,
  ADD COLUMN guest_pan VARCHAR(20) DEFAULT NULL;
